atat_build – BROWNPAK
atat_build Subroutine
29 statements
Source File
public subroutine atat_build(num_atoms, bonds, atbo_tab, atat_tab)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: num_atoms
integer, intent(in), dimension(:,:) :: bonds
type(itable_t), intent(in) :: atbo_tab
Atoms -> bonds table
type(itable_t), intent(out) :: atat_tab
Atoms -> bonded atoms table (1-ring)
Calls
Called by
Contents
None
Call graph
atat_build calls itbl_init, ivector_init
itbl_init calls ivector_init
ivector_init calls ivector_init, ivector_from_array
ivector_from_array calls ivector_init
pt_init calls atat_build
ia_setup calls pt_init
run calls ia_setup
main calls run