bds_integrate_fd – BROWNPAK
bds_integrate_fd Subroutine
23 statements
Source File
private subroutine bds_integrate_fd(ierr)
Performs one step of free-draining BD integeration.
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: ierr
Calls
Called by
Contents
None
Call graph
bds_integrate_fd calls calc_ambient_velocity, get_rv_gaussian, ia_calc_forces
get_rv_gaussian calls vdrnggaussian
ia_calc_forces calls ia_add_bond_forces, ia_add_vdw_forces_vl, ia_add_vdw_forces, ia_add_tether_forces, ia_add_external_forces, ia_add_vdw_forces_cl
ia_add_bond_forces calls ia_get_bond_force
ia_add_vdw_forces_vl calls verlet_build, ia_get_vdw_force
ia_add_vdw_forces calls ia_get_vdw_force
ia_add_tether_forces calls ia_get_tether_force
ia_add_vdw_forces_cl calls ia_get_vdw_force, cl_get_num_cells, cl_get_nbr_cells, cl_get_contents
bds_run calls bds_integrate_fd
main calls bds_run