bds_integrate_hi – BROWNPAK
bds_integrate_hi Subroutine
40 statements
Source File
private subroutine bds_integrate_hi(ierr)
Performs one step of BD integeration including HI.
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: ierr
Calls
Called by
Contents
None
Call graph
bds_integrate_hi calls potrf, str_from_num, ia_calc_forces, symv, calc_ambient_velocity, get_rv_gaussian, calc_rpy_tensor, calc_bdw_kryl, trmv
str_from_num calls str_from_inum, str_from_dnum, str_from_ilnum
ia_calc_forces calls ia_add_vdw_forces_vl, ia_add_external_forces, ia_add_bond_forces, ia_add_vdw_forces, ia_add_tether_forces, ia_add_vdw_forces_cl
get_rv_gaussian calls vdrnggaussian
ia_add_vdw_forces_vl calls ia_get_vdw_force, verlet_build
ia_add_bond_forces calls ia_get_bond_force
str_from_dnum calls str_trimzero
ia_add_vdw_forces calls ia_get_vdw_force
ia_add_tether_forces calls ia_get_tether_force
ia_add_vdw_forces_cl calls cl_get_num_cells, cl_get_contents, ia_get_vdw_force, cl_get_nbr_cells
bds_run calls bds_integrate_hi
main calls bds_run