bds_run – BROWNPAK
bds_run Subroutine
53 statements
Source File
public subroutine bds_run(nts_beg, simbox, atc, ierr)
Driver for BD integrator.
Repeatedly calls integrate_em or integrate_se to update atom positions.
Arguments
Type Intent Optional Attributes Name
integer(kind=ip_long), intent(in) :: nts_beg
type(smbx_t), intent(in), target :: simbox
type(atmcfg_t), intent(inout), target :: atc
integer, intent(out) :: ierr
Error flag
Calls
Called by
Contents
None
Call graph
bds_run calls str_from_num, integrate_em, integrate_se, stats_write, write_dump, stats_accumulate
integrate_em calls calc_drift, calc_diffusion
integrate_se calls calc_diffusion, nitsol
stats_accumulate calls compute_ic0, compute_ic1
calc_drift calls dsymv, ia_calc_forces
calc_diffusion calls calc_rpy_tensor, brn_calc_dw, brn_calc_bdw
ia_calc_forces calls ia_add_bond_forces, ia_add_vdw_forces, ia_add_tether_forces, ia_add_external_forces
brn_calc_dw calls get_rv_gaussian
brn_calc_bdw calls calc_bdw_blanc, calc_bdw_cholesky, calc_bdw_lanc
ia_add_bond_forces calls ia_get_bond_force
calc_bdw_blanc calls dsbevd, dorgqr, dgeqp3
calc_bdw_cholesky calls dtrmm, dpotrf
get_rv_gaussian calls vdrnggaussian
ia_add_vdw_forces calls pt_build, ia_get_vdw_force
ia_add_tether_forces calls ia_get_tether_force
ia_get_bond_force calls bond_harm, bond_fene, bond_kg, bond_ms
pt_build calls build_pt_cell_list, build_pt_n2, build_pt_aabbtree, build_pt_verlet
ia_get_tether_force calls teth_rigid, teth_harm
ia_get_vdw_force calls vdw_lj_coul_debye, vdw_cosine, vdw_gaussian, vdw_lj_coul, vdw_lj, vdw_dpd
build_pt_cell_list calls cl_build, cl_get_num_cells, cl_get_nbr_cells, cl_get_contents
bond_fene calls str_from_num
build_pt_aabbtree calls ivector_init
bond_kg calls str_from_num
bond_ms calls str_from_num
ivector_init calls ivector_init, ivector_from_array
str_from_num calls str_from_ilnum, str_from_inum, str_from_dnum
ivector_from_array calls ivector_init
str_from_dnum calls str_trimzero
run calls bds_run
main calls run