bond_ms – BROWNPAK
bond_ms Subroutine
24 statements
Source File
private subroutine bond_ms(r, params, enrg, frc, ierr)
Evaluates the potential & its derivative for Marko-Siggia bond. See bond_ms_set.
If bond length exceeds maximum extensible spring length, an error will be reported as ierr = 1.
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: r
real(kind=rp), intent(in), dimension(:) :: params
real(kind=rp), intent(out) :: enrg
real(kind=rp), intent(out) :: frc
integer, intent(out) :: ierr
Calls
Contents
None
Call graph
bond_ms calls str_from_num
str_from_num calls str_from_inum, str_from_dnum, str_from_ilnum
str_from_dnum calls str_trimzero