brn_calc_bdw – BROWNPAK
brn_calc_bdw Subroutine
20 statements
Source File
public subroutine brn_calc_bdw(mob, bdw, ierr, lconv, f)
Main driver routine for calculating B.dW.
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(inout), dimension(:,:) :: mob
(sizm,sizm) symmetric positive definite matrix. On entry, contains the mobility matrix. On return, if meth = 'CHOL', the upper triangular part is overwritten with the result of Cholesky decomposition. The strictly lower triangular part is left intact.
real(kind=rp), intent(inout), dimension(:,:) :: bdw
(sizm,s) matrix. On entry, contains s column vectors drawn from standard normal distribution. On return, the s columns are overwritten with the result of B.dW.
integer, intent(out) :: ierr
Error flag.
logical, intent(out), optional :: lconv
If meth = 'LANC', returns true if converged, false otherwise.
integer, intent(out), optional :: f
If meth = 'LANC', the number of iterations performed.
Calls
Called by
Contents
None
Call graph
brn_calc_bdw calls calc_bdw_cholesky, calc_bdw_lanc, calc_bdw_blanc
calc_bdw_cholesky calls dtrmm, dpotrf
calc_bdw_blanc calls dsbevd, dorgqr, dgeqp3
calc_diffusion calls brn_calc_bdw
integrate_em calls calc_diffusion
integrate_se calls calc_diffusion
bds_run calls integrate_em, integrate_se
run calls bds_run
main calls run