build_pt_aabbtree – BROWNPAK
build_pt_aabbtree Subroutine
30 statements
Source File
private subroutine build_pt_aabbtree(simbox, coordinates, pair_tab)
Arguments
Type Intent Optional Attributes Name
type(smbx_t), intent(in) :: simbox
real(kind=rp), intent(in), dimension(:,:) :: coordinates
type(itable_t), intent(inout) :: pair_tab
Calls
Called by
Contents
None
Call graph
build_pt_aabbtree calls ivector_init
ivector_init calls ivector_init, ivector_from_array
ivector_from_array calls ivector_init
pt_build calls build_pt_aabbtree
ia_add_vdw_forces calls pt_build
ia_calc_forces calls ia_add_vdw_forces
calc_drift calls ia_calc_forces
integrate_em calls calc_drift
se_fval calls calc_drift
bds_run calls integrate_em
run calls bds_run
main calls run