build_pt_cell_list – BROWNPAK
build_pt_cell_list Subroutine
57 statements
Source File
private subroutine build_pt_cell_list(simbox, coordinates, pair_tab)
Builds a pair table using cell list.
Arguments
Type Intent Optional Attributes Name
type(smbx_t), intent(in) :: simbox
real(kind=rp), intent(in), dimension(:,:) :: coordinates
type(itable_t), intent(inout) :: pair_tab
Calls
Called by
Contents
None
Call graph
build_pt_cell_list calls cl_get_contents, cl_build, cl_get_num_cells, cl_get_nbr_cells
pt_build calls build_pt_cell_list
ia_add_vdw_forces calls pt_build
ia_calc_forces calls ia_add_vdw_forces
calc_drift calls ia_calc_forces
integrate_em calls calc_drift
se_fval calls calc_drift
bds_run calls integrate_em
run calls bds_run
main calls run