calc_diffusion – BROWNPAK
calc_diffusion Subroutine
33 statements
Source File
private subroutine calc_diffusion(ierr)
Calculates the diffusion term of the SDE. Updates module variables diffusion and cntr_mobsam.
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: ierr
Calls
Called by
Contents
None
Call graph
calc_diffusion calls brn_calc_dw, brn_calc_bdw, calc_rpy_tensor
brn_calc_dw calls get_rv_gaussian
brn_calc_bdw calls calc_bdw_lanc, calc_bdw_cholesky, calc_bdw_blanc
calc_bdw_cholesky calls dtrmm, dpotrf
get_rv_gaussian calls vdrnggaussian
calc_bdw_blanc calls dsbevd, dorgqr, dgeqp3
integrate_em calls calc_diffusion
integrate_se calls calc_diffusion
bds_run calls integrate_em, integrate_se
run calls bds_run
main calls run