cl_get_contents – BROWNPAK
cl_get_contents Subroutine
9 statements
Source File
public subroutine cl_get_contents(ic, res)
Returns a pointer to the entries of cell with linear index ic.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ic
integer, intent(out), dimension(:), pointer :: res
Called by
Contents
None
Call graph
ia_add_vdw_forces_cl calls cl_get_contents
cl_print calls cl_get_contents
mpcd_collide calls cl_get_contents
ia_calc_forces calls ia_add_vdw_forces_cl
mpcd_run calls mpcd_collide, mpcd_stream
rlx_integrate calls ia_calc_forces
bds_integrate_fd calls ia_calc_forces
mpcd_stream calls ia_calc_forces
main calls mpcd_run, bds_run, rlx_run
bds_integrate_hi calls ia_calc_forces
bds_run calls bds_integrate_fd, bds_integrate_hi
rlx_run calls rlx_integrate