cl_get_nbr_cells – BROWNPAK
cl_get_nbr_cells Subroutine
9 statements
Source File
public subroutine cl_get_nbr_cells(ic, res)
Returns a pointer to the neighbor cells of cell with linear index ic.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ic
integer, intent(out), dimension(:), pointer :: res
Called by
Contents
None
Call graph
cl_print calls cl_get_nbr_cells
ia_add_vdw_forces_cl calls cl_get_nbr_cells
ia_calc_forces calls ia_add_vdw_forces_cl
mpcd_stream calls ia_calc_forces
bds_integrate_fd calls ia_calc_forces
bds_integrate_hi calls ia_calc_forces
rlx_integrate calls ia_calc_forces
bds_run calls bds_integrate_fd, bds_integrate_hi
mpcd_run calls mpcd_stream
rlx_run calls rlx_integrate
main calls bds_run, mpcd_run, rlx_run