cl_get_num_cells – BROWNPAK
cl_get_num_cells Function
4 statements
Source File
public function cl_get_num_cells() result(res)
Returns the total number of cells
Arguments
None
Return Value integer
Called by
Contents
None
Call graph
mpcd_collide calls cl_get_num_cells
ia_add_vdw_forces_cl calls cl_get_num_cells
mpcd_run calls mpcd_collide, mpcd_stream
ia_calc_forces calls ia_add_vdw_forces_cl
mpcd_stream calls ia_calc_forces
main calls mpcd_run, rlx_run, bds_run
bds_integrate_fd calls ia_calc_forces
rlx_integrate calls ia_calc_forces
bds_integrate_hi calls ia_calc_forces
rlx_run calls rlx_integrate
bds_run calls bds_integrate_fd, bds_integrate_hi