control_write – BROWNPAK
control_write Subroutine
55 statements
Source File
public subroutine control_write(this, fn)
Write simulation parameters to file
Arguments
Type Intent Optional Attributes Name
class(ctrlpar_t), intent(out) :: this
A ctrlpar_t instance.
character(len=*), intent(in) :: fn
Output file name
Calls
Contents
None
Call graph
control_write calls str_from_num
str_from_num calls str_from_ilnum, str_from_inum, str_from_dnum
str_from_dnum calls str_trimzero