control_read – BROWNPAK
control_read Subroutine
46 statements
Source File
public subroutine control_read(this, fn)
Reads simulation control parameters from file
Arguments
Type Intent Optional Attributes Name
class(ctrlpar_t), intent(out) :: this
A ctrlpar_t instance.
character(len=*), intent(in) :: fn
Name of parameters file.
Calls
Contents
None
Call graph
control_read calls readline, str_get_keyval, str_to_d
readline calls str_strip_comment, str_is_comment