det – BROWNPAK
det Function
15 statements
Source File
public function det(A) result(res)
Returns the determinant of an (N x N) matrix, where N = 2, 3, or 4.
Original routine by David Simpson
Note
For a general NxN matrix do an LU decomp
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in), dimension(:,:) :: A
(N,N) array, where N = 2, 3, or 4.
Return Value real(kind=rp)
Called by
Contents
None
Call graph
eigval_33rsym calls det
mpcd_collide calls det
mpcd_run calls mpcd_collide
main calls mpcd_run