dsyevc3 – BROWNPAK
dsyevc3 Subroutine
25 statements
Source File
private subroutine dsyevc3(A, W)
Calculates the eigenvalues of a symmetric 3x3 matrix A using Cardano's analytical algorithm. Only the diagonal and upper triangular parts of A are accessed. The access is read-only.
Copyright (C) 2006 Joachim Kopp
Arguments
Type Intent Optional Attributes Name
real(kind=RP), intent(in), DIMENSION(3,3) :: A
real(kind=RP), intent(out), DIMENSION(3) :: W(3)
Called by
Contents
None
Call graph
stats_compute_ic0 calls dsyevc3
stats_write calls stats_compute_ic0
bds_run calls stats_write
mpcd_run calls stats_write
main calls bds_run, mpcd_run