exat_build – BROWNPAK
exat_build Subroutine
44 statements
Source File
public subroutine exat_build()
Arguments
None
Calls
Called by
Contents
None
Call graph
exat_build calls atat_build, itbl_init, ivector_init
atat_build calls itbl_init, ivector_init
itbl_init calls ivector_init
ia_setup calls exat_build
setup calls ia_setup
main calls setup