finish – BROWNPAK
finish Subroutine
8 statements
Source File
public subroutine finish(atc)
Arguments
Type Intent Optional Attributes Name
type(atmcfg_t), intent(inout) :: atc
Calls
Called by
Contents
None
Call graph
finish calls ia_finish, stats_finish, bds_finish, atmcfg_delete
ia_finish calls pt_delete
stats_finish calls zero_out
bds_finish calls brn_finish
pt_delete calls cl_delete
run calls finish
main calls run