get_rv_gaussian – BROWNPAK
get_rv_gaussian Subroutine
35 statements
Source File
public subroutine get_rv_gaussian(mean, std_dev, rv, block_size)
Generates a random vector of integers from a gaussian distribution.
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: mean
real(kind=rp), intent(in) :: std_dev
real(kind=rp), intent(out), dimension(:) :: rv
integer(kind=ip), intent(in), optional :: block_size
Calls
Called by
Contents
None
Call graph
get_rv_gaussian calls vdrnggaussian
brn_calc_dw calls get_rv_gaussian
calc_diffusion calls brn_calc_dw
integrate_em calls calc_diffusion
integrate_se calls calc_diffusion
bds_run calls integrate_em, integrate_se
run calls bds_run
main calls run