get_rv_uniform – BROWNPAK
get_rv_uniform Subroutine
35 statements
Source File
public subroutine get_rv_uniform(lb, ub, rv, block_size)
Returns a random vector from a uniform distribution.
If a block_size > 0 is provided, it fills rv in blocks of size block_size.
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: lb
Lower bound
real(kind=rp), intent(in) :: ub
Upper bound
real(kind=rp), intent(out), dimension(:) :: rv
integer(kind=ip), intent(in), optional :: block_size
Calls
Called by
Contents
None
Call graph
get_rv_uniform calls vdrnguniform
mpcd_collide calls get_rv_uniform
ransphere calls get_rv_uniform
smbx_get_rnd_points calls get_rv_uniform
mpcd_run calls mpcd_collide
main calls mpcd_run