ia_add_vdw_forces – BROWNPAK
ia_add_vdw_forces Subroutine
48 statements
Source File
private subroutine ia_add_vdw_forces(simbox, atc, ierr)
Calculates force and energy due to all short-ranged non-bonded pairwise interactions based on pair_tab.
Arguments
Type Intent Optional Attributes Name
type(smbx_t), intent(in) :: simbox
type(atmcfg_t), intent(inout) :: atc
integer, intent(out) :: ierr
Calls
Called by
Contents
None
Call graph
ia_add_vdw_forces calls pt_build, ia_get_vdw_force
pt_build calls build_pt_cell_list, build_pt_n2, build_pt_aabbtree, build_pt_verlet
ia_get_vdw_force calls vdw_lj_coul_debye, vdw_cosine, vdw_gaussian, vdw_lj_coul, vdw_lj, vdw_dpd
build_pt_cell_list calls cl_build, cl_get_num_cells, cl_get_contents, cl_get_nbr_cells
build_pt_aabbtree calls ivector_init
ivector_init calls ivector_init, ivector_from_array
ivector_from_array calls ivector_init
ia_calc_forces calls ia_add_vdw_forces
calc_drift calls ia_calc_forces
integrate_em calls calc_drift
se_fval calls calc_drift
bds_run calls integrate_em
run calls bds_run
main calls run