ia_add_vdw_forces_cl – BROWNPAK
ia_add_vdw_forces_cl Subroutine
96 statements
Source File
private subroutine ia_add_vdw_forces_cl(ierr)
Calculates force and energy due to all short-ranged non-bonded pairwise interactions and adds to energy_vdw & 'forcesin modulem_globals`. Uses cell list.
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: ierr
Calls
Called by
Contents
None
Call graph
ia_add_vdw_forces_cl calls cl_get_num_cells, cl_get_nbr_cells, cl_get_contents, ia_get_vdw_force
ia_calc_forces calls ia_add_vdw_forces_cl
mpcd_stream calls ia_calc_forces
rlx_integrate calls ia_calc_forces
bds_integrate_hi calls ia_calc_forces
bds_integrate_fd calls ia_calc_forces
rlx_run calls rlx_integrate
bds_run calls bds_integrate_hi, bds_integrate_fd
mpcd_run calls mpcd_stream
main calls rlx_run, bds_run, mpcd_run