ia_add_bond_forces – BROWNPAK
ia_add_bond_forces Subroutine
40 statements
Source File
private subroutine ia_add_bond_forces(simbox, atc, ierr)
Calculates forces & energy due to all bonds. Will add to energy_bond & and 'forcesin modulem_globals`.
Arguments
Type Intent Optional Attributes Name
type(smbx_t), intent(in) :: simbox
type(atmcfg_t), intent(inout) :: atc
integer, intent(out) :: ierr
Calls
Called by
Contents
None
Call graph
ia_add_bond_forces calls ia_get_bond_force
ia_get_bond_force calls bond_harm, bond_fene, bond_kg, bond_ms
bond_fene calls str_from_num
bond_kg calls str_from_num
bond_ms calls str_from_num
str_from_num calls str_from_ilnum, str_from_inum, str_from_dnum
str_from_dnum calls str_trimzero
ia_calc_forces calls ia_add_bond_forces
calc_drift calls ia_calc_forces
integrate_em calls calc_drift
se_fval calls calc_drift
bds_run calls integrate_em
run calls bds_run
main calls run