ia_get_vdw_force – BROWNPAK
ia_get_vdw_force Subroutine
30 statements
Source File
public subroutine ia_get_vdw_force(rij_mag, qi, qj, typ, enrg, frc, ierr)
Calculates the energy & its derivative due to a single interacting pair of atoms.
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: rij_mag
Distance between two atoms
real(kind=rp), intent(in) :: qi
Charge on atom i
real(kind=rp), intent(in) :: qj
Charge on atom j
integer, intent(in) :: typ
Type of vdw interaction
real(kind=rp), intent(out) :: enrg
Energy
real(kind=rp), intent(out) :: frc
Derivative of the potential. This is the magnitude of force due to this potential.
integer, intent(out) :: ierr
Error flag
Called by
Contents
None
Call graph
ia_add_vdw_forces_vl calls ia_get_vdw_force
ia_add_vdw_forces calls ia_get_vdw_force
ia_add_vdw_forces_cl calls ia_get_vdw_force
ia_calc_forces calls ia_add_vdw_forces_vl, ia_add_vdw_forces, ia_add_vdw_forces_cl
mpcd_stream calls ia_calc_forces
bds_integrate_fd calls ia_calc_forces
bds_integrate_hi calls ia_calc_forces
rlx_integrate calls ia_calc_forces
bds_run calls bds_integrate_fd, bds_integrate_hi
mpcd_run calls mpcd_stream
rlx_run calls rlx_integrate
main calls bds_run, mpcd_run, rlx_run