ia_get_bond_force – BROWNPAK
ia_get_bond_force Subroutine
23 statements
Source File
public subroutine ia_get_bond_force(rij_mag, sty, params, enrg, frc, ierr)
Calculates the energy & its derivative due to a bond.
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: rij_mag
Distance between bonded atoms
integer, intent(in) :: sty
Style of the bond
real(kind=rp), intent(in), dimension(:) :: params
Parameters for bonded interaction
real(kind=rp), intent(out) :: enrg
Bond energy
real(kind=rp), intent(out) :: frc
Derivative of the potential. This is the magnitude of the force due to this potential.
integer, intent(out) :: ierr
Error flag
Calls
Called by
Contents
None
Call graph
ia_get_bond_force calls bond_harm, bond_fene, bond_kg, bond_ms
bond_fene calls str_from_num
bond_kg calls str_from_num
bond_ms calls str_from_num
str_from_num calls str_from_ilnum, str_from_inum, str_from_dnum
str_from_dnum calls str_trimzero
ia_add_bond_forces calls ia_get_bond_force
ia_calc_forces calls ia_add_bond_forces
calc_drift calls ia_calc_forces
integrate_em calls calc_drift
se_fval calls calc_drift
bds_run calls integrate_em
run calls bds_run
main calls run