ia_setup – BROWNPAK
ia_setup Subroutine
26 statements
Source File
public subroutine ia_setup(cpar, simbox, atc)
Builds necessary neighbor tables and sets up parameters for potentials.
Arguments
Type Intent Optional Attributes Name
type(ctrlpar_t), intent(in) :: cpar
type(smbx_t), intent(in) :: simbox
type(atmcfg_t), intent(inout) :: atc
Calls
Called by
Contents
None
Call graph
ia_setup calls ia_vdw_setup, ia_external_setup, ia_tether_setup, ia_angle_setup, ia_dihedral_setup, pt_init, ia_bond_setup
pt_init calls cl_init, atat_build, exat_build, cl_set_cell_size, itbl_init, cl_build_cell_nbrs
cl_init calls ivector_init
atat_build calls itbl_init, ivector_init
exat_build calls itbl_init, ivector_init
itbl_init calls ivector_init
ivector_init calls ivector_init, ivector_from_array
ivector_from_array calls ivector_init
run calls ia_setup
main calls run