integrate_se – BROWNPAK
integrate_se Subroutine
49 statements
Source File
private subroutine integrate_se(ierr)
Performs one step of BD integration using semi-implicit Euler scheme.
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: ierr
Calls
Called by
Contents
None
Call graph
integrate_se calls calc_diffusion, nitsol
calc_diffusion calls brn_calc_dw, brn_calc_bdw, calc_rpy_tensor
brn_calc_dw calls get_rv_gaussian
brn_calc_bdw calls calc_bdw_lanc, calc_bdw_cholesky, calc_bdw_blanc
calc_bdw_cholesky calls dtrmm, dpotrf
get_rv_gaussian calls vdrnggaussian
calc_bdw_blanc calls dsbevd, dorgqr, dgeqp3
bds_run calls integrate_se
run calls bds_run
main calls run