itbl_init – BROWNPAK
itbl_init Subroutine
16 statements
Source File
public subroutine itbl_init(this, num_rows, ierr)
Creates an empty itable_t with num_rows rows and all rows having zero elements.
Arguments
Type Intent Optional Attributes Name
type(itable_t), intent(inout) :: this
integer, intent(in) :: num_rows
Must be > 0
integer, intent(out), optional :: ierr
Calls
Called by
Contents
None
Call graph
itbl_init calls ivector_init
ivector_init calls ivector_init, ivector_from_array
ivector_from_array calls ivector_init
atat_build calls itbl_init
exat_build calls itbl_init
atan_build calls itbl_init
atbo_build calls itbl_init
pt_init calls itbl_init, atat_build, exat_build
atdh_build calls itbl_init
ia_setup calls pt_init
run calls ia_setup
main calls run