mpcd_run – BROWNPAK
mpcd_run Subroutine
47 statements
Source File
public subroutine mpcd_run()
Driver for MPCD integrator.
Repeatedly calls mpcd_stream and mpcd_collide to update atom positions.
Handling of flow field is not imlemented yet. If a non-zero flow_style is specified, it will be set to zero.
Arguments
None
Calls
Called by
Contents
None
Call graph
mpcd_run calls mpcd_stream, mpcd_collide, stats_write, str_from_num, stats_finish
mpcd_stream calls ia_calc_forces
mpcd_collide calls invert_mat33, cl_get_num_cells, cl_get_contents, cl_set_cell_size, cross, det, get_rv_uniform, cl_build, gelsy
stats_write calls stats_compute_ic1, stats_compute_ic0
str_from_num calls str_from_inum, str_from_dnum, str_from_ilnum
get_rv_uniform calls vdrnguniform
str_from_dnum calls str_trimzero
stats_compute_ic0 calls dsyevc3
ia_calc_forces calls ia_add_vdw_forces_vl, ia_add_external_forces, ia_add_bond_forces, ia_add_vdw_forces, ia_add_tether_forces, ia_add_vdw_forces_cl
ia_add_vdw_forces_vl calls ia_get_vdw_force, verlet_build
ia_add_bond_forces calls ia_get_bond_force
ia_add_vdw_forces calls ia_get_vdw_force
ia_add_tether_forces calls ia_get_tether_force
ia_add_vdw_forces_cl calls cl_get_num_cells, cl_get_contents, ia_get_vdw_force, cl_get_nbr_cells
main calls mpcd_run