nitdrv – BROWNPAK
nitdrv Subroutine
192 statements
Source File
subroutine nitdrv(n, xcur, fcur, xpls, fpls, step, f, jacv, rpar, ipar, ftol, stptol, nnimax, ijacv, ikrysl, kdmax, irpre, iksmax, iresup, ifdord, ibtmax, ieta, iterm, nfe, njve, nrpre, nli, nni, nbt, rwork, dinpr, dnorm)
Arguments
Type Intent Optional Attributes Name
integer :: n
double precision :: xcur(n)
double precision :: fcur(n)
double precision :: xpls(n)
double precision :: fpls(n)
double precision :: step(n)
real :: f
integer :: jacv
double precision :: rpar(*)
integer :: ipar(*)
double precision :: ftol
double precision :: stptol
integer :: nnimax
integer :: ijacv
integer :: ikrysl
integer :: kdmax
integer :: irpre
integer :: iksmax
integer :: iresup
integer :: ifdord
integer :: ibtmax
integer :: ieta
integer :: iterm
integer :: nfe
integer :: njve
integer :: nrpre
integer :: nli
integer :: nni
integer :: nbt
double precision :: rwork(*)
double precision :: dinpr
double precision :: dnorm
Calls
Contents
Common Blocks
nitprint nitinfo nitparam
Common Blocks
common /nitprint/
Type Attributes Name Initial
integer :: iplvl
integer :: ipunit
common /nitinfo/
Type Attributes Name Initial
double precision :: avrate
double precision :: fcurnrm
integer :: instep
integer :: newstep
integer :: krystat
common /nitparam/
Type Attributes Name Initial
double precision :: choice1_exp
double precision :: choice2_exp
double precision :: choice2_coef
double precision :: eta_cutoff
double precision :: etamax
double precision :: thmin
double precision :: thmax
double precision :: etafixed
Call graph
nitdrv calls dfloat, dlamch, dcopy, nitbt
nitbt calls dscal, 2