nitgm – BROWNPAK
nitgm Subroutine
190 statements
Source File
subroutine nitgm(n, xcur, fcur, fcnrm, step, eta, f, jacv, rpar, ipar, ijacv, irpre, iksmax, iresup, ifdord, nfe, njve, nrpre, nli, kdmax, kdmaxp1, vv, rr, svbig, svsml, w, rwork, rsnrm, dinpr, dnorm, itrmks)
Arguments
Type Intent Optional Attributes Name
integer :: n
double precision :: xcur(n)
double precision :: fcur(n)
double precision :: fcnrm
double precision :: step(n)
double precision :: eta
real :: f
integer :: jacv
double precision :: rpar(*)
integer :: ipar(*)
integer :: ijacv
integer :: irpre
integer :: iksmax
integer :: iresup
integer :: ifdord
integer :: nfe
integer :: njve
integer :: nrpre
integer :: nli
integer :: kdmax
integer :: kdmaxp1
double precision :: vv(n,kdmaxp1)
double precision :: rr(kdmax,kdmax)
double precision :: svbig(kdmax)
double precision :: svsml(kdmax)
double precision :: w(kdmax)
double precision :: rwork(n)
double precision :: rsnrm
double precision :: dinpr
double precision :: dnorm
integer :: itrmks
Calls
Contents
Common Blocks
nitprint
Common Blocks
common /nitprint/
Type Attributes Name Initial
integer :: iplvl
integer :: ipunit
Call graph
nitgm calls dfloat, dacos, daxpy, dlamch, dscal, dsin, dcopy, 2