nitjv – BROWNPAK
nitjv Subroutine
30 statements
Source File
subroutine nitjv(n, xcur, fcur, f, jacv, rpar, ipar, ijacv, ifdord, itask, nfe, njve, nrpre, v, z, rwork1, rwork2, dnorm, itrmjv)
Arguments
Type Intent Optional Attributes Name
integer :: n
double precision :: xcur(n)
double precision :: fcur(n)
real :: f
integer :: jacv
double precision :: rpar(*)
integer :: ipar(*)
integer :: ijacv
integer :: ifdord
integer :: itask
integer :: nfe
integer :: njve
integer :: nrpre
double precision :: v(n)
double precision :: z(n)
double precision :: rwork1(n)
double precision :: rwork2(n)
double precision :: dnorm
integer :: itrmjv
Calls
Called by
Contents
Common Blocks
nitprint
Common Blocks
common /nitprint/
Type Attributes Name Initial
integer :: iplvl
integer :: ipunit
Call graph
nitjv calls dcopy, nitfd
nitfd calls dlamch, daxpy, dscal
nitstb calls nitjv
nittfq calls nitjv