nitsol – BROWNPAK
nitsol Subroutine
156 statements
Source File
subroutine nitsol(n, x, f, jacv, ftol, stptol, input, info, rwork, rpar, ipar, iterm, dinpr, dnorm)
Arguments
Type Intent Optional Attributes Name
integer :: n
double precision :: x(n)
real :: f
integer :: jacv
double precision :: ftol
double precision :: stptol
integer :: input(10)
integer :: info(6)
double precision :: rwork(*)
double precision :: rpar(*)
integer :: ipar(*)
integer :: iterm
double precision :: dinpr
double precision :: dnorm
Called by
Contents
Common Blocks
nitprint nitinfo nitparam
Common Blocks
common /nitprint/
Type Attributes Name Initial
integer :: iplvl
integer :: ipunit
common /nitinfo/
Type Attributes Name Initial
double precision :: avrate
double precision :: fcurnrm
integer :: instep
integer :: newstep
integer :: krystat
common /nitparam/
Type Attributes Name Initial
double precision :: choice1_exp
double precision :: choice2_exp
double precision :: choice2_coef
double precision :: eta_cutoff
double precision :: etamax
double precision :: thmin
double precision :: thmax
double precision :: etafixed
Call graph
integrate_se calls nitsol
bds_run calls integrate_se
run calls bds_run
main calls run