nittfq – BROWNPAK
nittfq Subroutine
229 statements
Source File
subroutine nittfq(n, xcur, fcur, fcnrm, step, eta, f, jacv, rpar, ipar, ijacv, irpre, iksmax, ifdord, nfe, njve, nrpre, nli, r, rcgs, rtil, d, p, q, u, v, y, rwork1, rwork2, rsnrm, dinpr, dnorm, itrmks)
Arguments
Type Intent Optional Attributes Name
integer :: n
double precision :: xcur(n)
double precision :: fcur(n)
double precision :: fcnrm
double precision :: step(n)
double precision :: eta
real :: f
integer :: jacv
double precision :: rpar(*)
integer :: ipar(*)
integer :: ijacv
integer :: irpre
integer :: iksmax
integer :: ifdord
integer :: nfe
integer :: njve
integer :: nrpre
integer :: nli
double precision :: r(n)
double precision :: rcgs(n)
double precision :: rtil(n)
double precision :: d(n)
double precision :: p(n)
double precision :: q(n)
double precision :: u(n)
double precision :: v(n)
double precision :: y(n)
double precision :: rwork1(n)
double precision :: rwork2(n)
double precision :: rsnrm
double precision :: dinpr
double precision :: dnorm
integer :: itrmks
Calls
Contents
Common Blocks
nitprint
Common Blocks
common /nitprint/
Type Attributes Name Initial
integer :: iplvl
integer :: ipunit
Call graph
nittfq calls nitjv, daxpy, dlamch, dscal, dswap, dcopy
nitjv calls dcopy, nitfd
nitfd calls daxpy, dlamch, dscal