pt_init – BROWNPAK
pt_init Subroutine
38 statements
Source File
public subroutine pt_init(mth, num_atoms, excl_atoms, rcut, tskn, bonds, simbox, pair_tab)
Performs initial setup for building a pair list.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: mth
integer, intent(in) :: num_atoms
integer, intent(in) :: excl_atoms
real(kind=rp), intent(in) :: rcut
real(kind=rp), intent(in) :: tskn
integer, intent(in), dimension(:,:) :: bonds
type(smbx_t), intent(in) :: simbox
type(itable_t), intent(inout) :: pair_tab
Calls
Called by
Contents
None
Call graph
pt_init calls cl_init, atat_build, exat_build, cl_set_cell_size, itbl_init, cl_build_cell_nbrs
cl_init calls ivector_init
atat_build calls itbl_init, ivector_init
exat_build calls itbl_init, ivector_init
itbl_init calls ivector_init
ivector_init calls ivector_init, ivector_from_array
ivector_from_array calls ivector_init
ia_setup calls pt_init
run calls ia_setup
main calls run