readline – BROWNPAK
readline Subroutine
14 statements
Source File
public subroutine readline(nunitr, line, comment_str, ios)
Reads a line from unit=nunitr, ignoring blank lines and deleting comments
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nunitr
character(len=*), intent(inout) :: line
character(len=*), intent(in) :: comment_str
integer, intent(out) :: ios
Calls
Called by
Contents
None
Call graph
readline calls str_strip_comment, str_is_comment
read_config calls readline
control_read calls readline
run calls read_config
main calls run