read_config – BROWNPAK
read_config Subroutine
253 statements
Source File
public subroutine read_config(simbox, atc, fn)
Read from CONFIG file
Arguments
Type Intent Optional Attributes Name
type(smbx_t), intent(out) :: simbox
type(atmcfg_t), intent(out) :: atc
character(len=*), intent(in) :: fn
Calls
Called by
Contents
None
Call graph
read_config calls str_startswith, readline, str_to_i, str_split
readline calls str_strip_comment, str_is_comment
str_split calls str_compact
run calls read_config
main calls run