rlx_run – BROWNPAK
rlx_run Subroutine
46 statements
Source File
public subroutine rlx_run()
Driver for relaxation
Arguments
None
Calls
Called by
Contents
None
Call graph
rlx_run calls rlx_integrate, str_from_num, str_strip, write_config, write_ldf
rlx_integrate calls ia_calc_forces
str_from_num calls str_from_dnum, str_from_inum, str_from_ilnum
str_from_dnum calls str_trimzero
ia_calc_forces calls ia_add_vdw_forces_cl, ia_add_vdw_forces_vl, ia_add_external_forces, ia_add_bond_forces, ia_add_vdw_forces, ia_add_tether_forces
ia_add_vdw_forces_cl calls cl_get_contents, ia_get_vdw_force, cl_get_num_cells, cl_get_nbr_cells
ia_add_vdw_forces_vl calls verlet_build, ia_get_vdw_force
ia_add_bond_forces calls ia_get_bond_force
ia_add_vdw_forces calls ia_get_vdw_force
ia_add_tether_forces calls ia_get_tether_force
main calls rlx_run