rlx_integrate – BROWNPAK
rlx_integrate Subroutine
19 statements
Source File
private subroutine rlx_integrate(ierr, zf)
Performs one step of relaxation
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: ierr
logical, intent(out) :: zf
Calls
Called by
Contents
None
Call graph
rlx_integrate calls ia_calc_forces
ia_calc_forces calls ia_add_vdw_forces_vl, ia_add_external_forces, ia_add_bond_forces, ia_add_vdw_forces, ia_add_tether_forces, ia_add_vdw_forces_cl
ia_add_vdw_forces_vl calls ia_get_vdw_force, verlet_build
ia_add_bond_forces calls ia_get_bond_force
ia_add_vdw_forces calls ia_get_vdw_force
ia_add_tether_forces calls ia_get_tether_force
ia_add_vdw_forces_cl calls cl_get_num_cells, cl_get_contents, ia_get_vdw_force, cl_get_nbr_cells
rlx_run calls rlx_integrate
main calls rlx_run