se_fval – BROWNPAK
se_fval Subroutine
18 statements
Source File
public subroutine se_fval(n, xcur, fcur, rpar, ipar, ierr)
Calculates the nonlinear function.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=rp), intent(in), dimension(*) :: xcur
real(kind=rp), intent(out), dimension(*) :: fcur
real(kind=rp), intent(in), dimension(*) :: rpar
integer, intent(in), dimension(*) :: ipar
integer, intent(out) :: ierr
Calls
Contents
None
Call graph
se_fval calls calc_drift
calc_drift calls ia_calc_forces, dsymv
ia_calc_forces calls ia_add_external_forces, ia_add_bond_forces, ia_add_vdw_forces, ia_add_tether_forces
ia_add_bond_forces calls ia_get_bond_force
ia_add_vdw_forces calls ia_get_vdw_force, pt_build
ia_add_tether_forces calls ia_get_tether_force
ia_get_vdw_force calls vdw_lj_coul_debye, vdw_cosine, vdw_gaussian, vdw_lj, vdw_dpd, vdw_lj_coul
ia_get_bond_force calls bond_fene, bond_harm, bond_kg, bond_ms
pt_build calls build_pt_cell_list, build_pt_n2, build_pt_aabbtree, build_pt_verlet
ia_get_tether_force calls teth_rigid, teth_harm
build_pt_cell_list calls cl_build, cl_get_num_cells, cl_get_nbr_cells, cl_get_contents
bond_fene calls str_from_num
bond_kg calls str_from_num
build_pt_aabbtree calls ivector_init
bond_ms calls str_from_num
ivector_init calls ivector_init, ivector_from_array
str_from_num calls str_from_ilnum, str_from_inum, str_from_dnum
ivector_from_array calls ivector_init
str_from_dnum calls str_trimzero