setup – BROWNPAK
setup Subroutine
32 statements
Source File
public subroutine setup()
Arguments
None
Calls
Called by
Contents
None
Call graph
setup calls ia_setup, smbx_init, init_stream, stats_init, mpcd_init, bds_init
ia_setup calls cl_set_cell_size, atbo_build, cl_build_cell_nbrs, exat_build, cl_init
init_stream calls vslnewstream
stats_init calls stats_write_hdr
atbo_build calls itbl_init
exat_build calls itbl_init, ivector_init, atat_build
cl_init calls ivector_init
itbl_init calls ivector_init
atat_build calls itbl_init, ivector_init
main calls setup