stats_accumulate – BROWNPAK
stats_accumulate Subroutine
47 statements
Source File
public subroutine stats_accumulate(simbox, atc)
Accumulates statistics.
Arguments
Type Intent Optional Attributes Name
type(smbx_t), intent(in) :: simbox
type(atmcfg_t), intent(in) :: atc
Calls
Called by
Contents
None
Call graph
stats_accumulate calls compute_ic0, compute_ic1
bds_run calls stats_accumulate
run calls bds_run
main calls run