str_from_ilnum – BROWNPAK
str_from_ilnum Function
11 statements
Source File
private pure function str_from_ilnum(num, frmt) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip_long), intent(in) :: num
character(len=*), intent(in), optional :: frmt
Return Value character(len=:), allocatable
Called by
Contents
None
Call graph
str_from_num calls str_from_ilnum
rlx_run calls str_from_num
bond_ms calls str_from_num
bds_integrate_hi calls str_from_num
bond_fene calls str_from_num
bds_run calls str_from_num, bds_integrate_hi
mpcd_run calls str_from_num
bond_kg calls str_from_num
main calls rlx_run, bds_run, mpcd_run