str_from_inum – BROWNPAK
str_from_inum Function
11 statements
Source File
private pure function str_from_inum(num, frmt) result(str)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: num
character(len=*), intent(in), optional :: frmt
Return Value character(len=:), allocatable
Called by
Contents
None
Call graph
str_from_num calls str_from_inum
bond_fene calls str_from_num
node_asstr calls str_from_num, node_asstr
aabb_print calls str_from_num
control_write calls str_from_num
bond_kg calls str_from_num
bond_ms calls str_from_num
ia_get_bond_force calls bond_fene, bond_kg, bond_ms
ia_add_bond_forces calls ia_get_bond_force
ia_calc_forces calls ia_add_bond_forces
calc_drift calls ia_calc_forces
integrate_em calls calc_drift
se_fval calls calc_drift
bds_run calls integrate_em
run calls bds_run
main calls run