allclose – BROWNPAK
allclose Interface
5 statements
Source File
public interface allclose
Checks if two arrays are elementwise close within tolerance
Calls
Contents
Module Procedures
allclose_rank1 allclose_rank2 allclose_rank3
Module Procedures
public function allclose_rank1(a, b, rel_tol, abs_tol)
Checks if two rank-1 floating point arrays of type double are close within tolerance.
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in), dimension(:) :: a
(m,) array
real(kind=rp), intent(in), dimension(:) :: b
(m,) array
real(kind=rp), intent(in), optional :: rel_tol
Relative tolerance; default 1e-10
real(kind=rp), intent(in), optional :: abs_tol
Absolute tolerance; default 0.0
Return Value logical
public function allclose_rank2(a, b, rel_tol, abs_tol)
Checks if two rank-2 floating point arrays of type double are close within tolerance.
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in), dimension(:,:) :: a
(m,n) array
real(kind=rp), intent(in), dimension(:,:) :: b
(m,n) array
real(kind=rp), intent(in), optional :: rel_tol
Relative tolerance; default 1e-10
real(kind=rp), intent(in), optional :: abs_tol
Absolute tolerance; default 0.0
Return Value logical
public function allclose_rank3(a, b, rel_tol, abs_tol)
Checks if two rank-3 floating point arrays of type double are close within tolerance.
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in), dimension(:,:,:) :: a
(m,n,p) array
real(kind=rp), intent(in), dimension(:,:,:) :: b
(m,n,p) array
real(kind=rp), intent(in), optional :: rel_tol
Relative tolerance; default 1e-10
real(kind=rp), intent(in), optional :: abs_tol
Absolute tolerance; default 0.0
Return Value logical
Call graph
allclose calls allclose_rank2, allclose_rank1, allclose_rank3
allclose_rank2 calls isclose
allclose_rank1 calls isclose
allclose_rank3 calls isclose