assignment(=) – BROWNPAK
assignment(=) Interface
5 statements
Source File
public interface assignment(=)
Calls
Contents
Module Procedures
ivector_assign dvector_assign i_dvector_assign
Module Procedures
public subroutine ivector_assign(this, other)
Copies the contents of ivector other to ivector this
Arguments
Type Intent Optional Attributes Name
class(ivector_t), intent(inout) :: this
class(ivector_t), intent(in) :: other
public subroutine dvector_assign(this, other)
Copies the contents of dvector other to dvector this
Arguments
Type Intent Optional Attributes Name
class(dvector_t), intent(inout) :: this
class(dvector_t), intent(in) :: other
public subroutine i_dvector_assign(this, other)
Copies the contents of ivector other to dvector this. Integers are cast to reals.
Arguments
Type Intent Optional Attributes Name
class(dvector_t), intent(inout) :: this
class(ivector_t), intent(in) :: other
Call graph
assignment(=) calls ivector_assign, dvector_assign, i_dvector_assign