ivector_init – BROWNPAK
ivector_init Interface
4 statements
Source File
public interface ivector_init
Calls
Called by
Contents
Module Procedures
ivector_init ivector_from_array
Module Procedures
public interface ivector_init()
Arguments
None
public subroutine ivector_from_array(this, x)
Creates an ivector with all elements from an array
Arguments
Type Intent Optional Attributes Name
type(ivector_t), intent(inout) :: this
integer, intent(in), dimension(:) :: x
Call graph
ivector_init calls ivector_init, ivector_from_array
ivector_from_array calls ivector_init
cl_init calls ivector_init
atat_build calls ivector_init, itbl_init
exat_build calls ivector_init, itbl_init
rebuild calls ivector_init, rebuild
itbl_init calls ivector_init
init calls ivector_init, init
build_pt_aabbtree calls ivector_init
pt_build calls build_pt_aabbtree
atan_build calls itbl_init
atbo_build calls itbl_init
pt_init calls cl_init, atat_build, exat_build, itbl_init
atdh_build calls itbl_init
ia_setup calls pt_init
ia_add_vdw_forces calls pt_build
ia_calc_forces calls ia_add_vdw_forces
run calls ia_setup, bds_run
main calls run
calc_drift calls ia_calc_forces
integrate_em calls calc_drift
se_fval calls calc_drift
bds_run calls integrate_em