node_asstr – BROWNPAK
node_asstr Interface
133 statements
Source File
interface
Calls
private module function node_asstr(this, frmt) result(buf) Implementation →
Arguments
Type Intent Optional Attributes Name
class(node_t), intent(in) :: this
A node_t instance.
character(len=*), intent(in), optional :: frmt
Format string for real numbers, e.g. '(f15.6)'. Default: (g0.6).
Return Value character(len=:), allocatable
Return value
Description
Returns a string representation of a node.
Call graph
node_asstr calls node_asstr, str_from_num
str_from_num calls str_from_ilnum, str_from_inum, str_from_dnum
str_from_dnum calls str_trimzero