main – BROWNPAK
main Program
39 statements
Source File
Uses
constants_m
strings_m
logger_m
control_m
setup_m
Calls
Contents
Variables
cla key val job_tag fn_control cpar ierr icla ncla
Variables
Type Attributes Name Initial
character(len=64) :: cla
character(len=:), allocatable :: key
character(len=:), allocatable :: val
character(len=:), allocatable :: job_tag
character(len=:), allocatable :: fn_control
type(ctrlpar_t) :: cpar
integer :: ierr
integer :: icla
integer :: ncla
Call graph
main calls run, str_get_keyval
run calls finish, read_config, bds_init, stats_init, init_stream, bds_run, read_dump, ia_setup
finish calls ia_finish, atmcfg_delete, bds_finish, stats_finish
read_config calls str_to_i, readline, str_startswith, str_split
bds_init calls brn_init
stats_init calls write_hdr, zero_out
init_stream calls vslnewstream
bds_run calls str_from_num, integrate_em, integrate_se, write_dump, stats_accumulate, stats_write
ia_setup calls ia_vdw_setup, ia_dihedral_setup, pt_init, ia_tether_setup, ia_external_setup, ia_angle_setup, ia_bond_setup
ia_finish calls pt_delete
readline calls str_is_comment, str_strip_comment
pt_init calls cl_init, atat_build, exat_build, cl_set_cell_size, itbl_init, cl_build_cell_nbrs
integrate_em calls calc_drift, calc_diffusion
integrate_se calls calc_diffusion, nitsol
stats_accumulate calls compute_ic0, compute_ic1
str_split calls str_compact
bds_finish calls brn_finish
stats_finish calls zero_out
pt_delete calls cl_delete
calc_drift calls dsymv, ia_calc_forces
cl_init calls ivector_init
atat_build calls itbl_init, ivector_init
calc_diffusion calls calc_rpy_tensor, brn_calc_dw, brn_calc_bdw
exat_build calls itbl_init, ivector_init
itbl_init calls ivector_init
ivector_init calls ivector_init, ivector_from_array
ia_calc_forces calls ia_add_bond_forces, ia_add_vdw_forces, ia_add_tether_forces, ia_add_external_forces
brn_calc_dw calls get_rv_gaussian
brn_calc_bdw calls calc_bdw_blanc, calc_bdw_cholesky, calc_bdw_lanc
ia_add_bond_forces calls ia_get_bond_force
calc_bdw_blanc calls dsbevd, dorgqr, dgeqp3
calc_bdw_cholesky calls dtrmm, dpotrf
ia_add_vdw_forces calls pt_build, ia_get_vdw_force
get_rv_gaussian calls vdrnggaussian
ia_add_tether_forces calls ia_get_tether_force
ivector_from_array calls ivector_init
ia_get_bond_force calls bond_harm, bond_fene, bond_kg, bond_ms
pt_build calls build_pt_cell_list, build_pt_n2, build_pt_aabbtree, build_pt_verlet
ia_get_tether_force calls teth_rigid, teth_harm
ia_get_vdw_force calls vdw_lj_coul_debye, vdw_cosine, vdw_gaussian, vdw_lj_coul, vdw_lj, vdw_dpd
build_pt_cell_list calls cl_build, cl_get_num_cells, cl_get_nbr_cells, cl_get_contents
bond_fene calls str_from_num
build_pt_aabbtree calls ivector_init
bond_kg calls str_from_num
bond_ms calls str_from_num
str_from_num calls str_from_ilnum, str_from_inum, str_from_dnum
str_from_dnum calls str_trimzero